config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :feeds do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_image, ImageUploader
  has_secure_password
  validates :profile_image, presence: true
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
  before_validation { email.downcase! }
  has_many :feeds
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required
   private
   def login_required
     redirect_to new_session_path unless current_user
   end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_path, notice: "#{favorite.feed.user.name}さんの投稿をお気に入りに登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_path, notice: "#{favorite.feed.user.name}さんの投稿をお気に入り解除しました"
  end
  def index
    @favorite = current_user.favorites
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: %i[ show edit update destroy ]
  before_action :login_only_operation, only: %i[ edit update destroy ]

  # GET /feeds or /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1 or /feeds/1.json
  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  # GET /feeds/new
  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds or /feeds.json
  def create
    @feed = current_user.feeds.build(feed_params)
    respond_to do |format|
      if @feed.save
        FeedMailer.feed_mail(@feed).deliver
        format.html { redirect_to @feed, notice: "投稿ができました" }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1 or /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: "編集しました" }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1 or /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: "削除しました" }
      format.json { head :no_content }
    end
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new if @feed.invalid?
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end
  def feed_params
    params.require(:feed).permit(:image, :image_cache, :content)
  end
  def login_only_operation
    redirect_to feeds_path unless @feed.user == current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [ :show, :edit, :update ]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
  end
  def edit
  end
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールの編集をしました"
    else
      render :edit
    end
  end
  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:profile_image, :profile_image_cache, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end    
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1>いいねした写真</h1>

<% @favorite.each do |favorite| %>
  <tr>
    <td><%= image_tag favorite.feed.image.url %></td>
  </tr>
<% end %>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true, url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li class="error_message"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
    <label>
      <%= form.file_field :image %>
    </label>
    <%= form.hidden_field :image_cache %>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>Post confirmation screen</h1>
<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>Content:<%= @feed.content %></p>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>
<%= form_with(model:@feed, url:new_feed_path, local:true, method: "get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "Back", name: "back" %>
<%  end %>

app/views/feeds/edit.html.erb
<h1>投稿編集画面</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'show', @feed %> |
<%= link_to 'back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Feeds</h1>

<div>
  <table>
    <thead>
      <tr>
        <th>Image</th>
        <th>Content</th>
        <th>User</th>
      </tr>
    </thead>

    <tbody>
        <% @feeds.each do |feed| %>
        <tr>
          <td><%= image_tag feed.image.url %></td>
          <td><%= feed.content %></td>
          <td><%= feed.user.name %></td>
          <td><%= link_to 'Show', feed, class: 'btn btn-info' %></td>
          <% if feed.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_feed_path(feed), class: 'btn btn-warning' %></td>
          <td><%= link_to 'Destroy', feed, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?'} %></td>
          <% end %>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'back', feeds_path %>

app/views/feeds/show.html.erb
<p class="feed_show">
  <strong>image:</strong>
  <%= image_tag @feed.image.url %>
  <strong>content:</strong>
  <%= @feed.content %>
</p>


<% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入りを解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りにする', favorites_path(feed_id: @feed.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<% if @feed.user_id == current_user.id %>
  <%= link_to 'edit', edit_feed_path(@feed) %> |
<% end %>
<%= link_to 'back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSharing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul class="top_menu">
        <% if logged_in? %>
          <li><%= link_to "Profile", user_path(current_user.id) %></li>
          <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
          <li><%= link_to 'New Feed', new_feed_path %></li>
          <li><%= link_to 'Index Feed', feeds_path %></li>
          <li><%= link_to 'favorites', favorites_path %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Login", new_session_path %></li>
        <% end %>
      </ul>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}")%>
      <% end %>
    </header>
    <%= yield %>
    <footer>
      <p>運営会社 写真共有株式会社</p>
      <p>© 2021- Photo sharing Corp.</p>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error")%> prohibited this <%= @user.name %> form being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li class="error_message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="sing_up_form">
  <%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :profile_image %>
  <label>
    <%= f.file_field :profile_image %>
  </label>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User account</h1>
<%= render 'form' %>

<%= link_to 'User account information', user_path(@user.id) %>

app/views/users/new.html.erb
<h1>Sing up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>User account information</h1>
<%= image_tag @user.profile_image.url %>
<h1><%= @user.name %>のページ</h1>
<p>Email: <%= @user.email %></p>

<%= link_to 'Editing User account', edit_user_path(@user) %>